
ARG IMAGE_VERSION

FROM l4d2server_base:${IMAGE_VERSION}

ARG SERVER_UNAME
ARG SERVER_UID
ARG SERVER_GNAME
ARG SERVER_GID
ARG SERVER_PASS

USER root
COPY server.cfg /tmp
RUN chown ${SERVER_UNAME}:${SERVER_GNAME} /tmp/server.cfg
COPY setup.sh /entrypoint/setup.sh
RUN chown ${SERVER_UNAME}:${SERVER_GNAME} /entrypoint/setup.sh

USER ${SERVER_UNAME}
ENTRYPOINT ["/entrypoint/setup.sh"]
