
ARG IMAGE_VERSION

FROM l4d2server_base:${IMAGE_VERSION}

ARG SERVER_UNAME
ARG SERVER_UID
ARG SERVER_PASS

USER root
COPY cfg/ /tmp/cfg/
RUN chown -R ${SERVER_UNAME}:${SERVER_GNAME} /tmp/cfg && \
    chmod -R +xr /tmp/cfg
COPY install-script.list /tmp
RUN chown ${SERVER_UNAME}:${SERVER_GNAME} /tmp/install-script.list && \
    chmod +xr /tmp/install-script.list
COPY install-script/ /tmp/install-script/
RUN chown -R ${SERVER_UNAME}:${SERVER_GNAME} /tmp/install-script && \
    chmod -R +xr /tmp/install-script
COPY setup.sh /entrypoint/setup.sh
RUN chown ${SERVER_UNAME}:${SERVER_GNAME} /entrypoint/setup.sh && \
    chmod +xr /entrypoint/setup.sh

USER ${SERVER_UNAME}
ENTRYPOINT /entrypoint/setup.sh

