
FROM cm2network/steamcmd:latest

ARG IMAGE_VERSION
ARG SERVER_UNAME
ARG SERVER_UID
ARG SERVER_GNAME
ARG SERVER_GID
ARG SERVER_PASS

##################################
# ディレクトリのセットアップ
##################################
RUN mkdir /entrypoint && \
    chown ${SERVER_UNAME}:${SERVER_GNAME} /entrypoint

RUN id
