
ARG IMAGE_VERSION

FROM l4d2server_base:${IMAGE_VERSION}

ARG SERVER_UNAME
ARG SERVER_UID
ARG SERVER_PASS

USER root
COPY boot.sh /entrypoint/boot.sh
RUN chown ${SERVER_UNAME} /entrypoint/boot.sh && \
    chmod +xr /entrypoint/boot.sh

USER ${SERVER_UNAME}
ENTRYPOINT /entrypoint/boot.sh
